# -*- coding: utf-8 -*-
"""[PTDLCB]Thuchanh28.9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yIeYnDS7qtHM0P8-s6lzqbfxdVJoT71G
"""


pip install pandas
import streamlit as st
import pandas as pd

url = 'https://docs.google.com/spreadsheets/d/1ukptB00bVPnIkSin93AMLR8IaWwIRyUg/edit?usp=sharing&ouid=110136132342245561127&rtpof=true&sd=true'
url = 'https://drive.google.com/uc?id=' + url.split('/')[-2]
df_pokemon = pd.read_excel(url)
df_pokemon.head(10)

# Thay thế các giá trị trong type2 bằng None
df_pokemon['type2'].fillna('None', inplace=True)

# Thay thế các giá trị trong height_m bằng Mode của tất cả các cột
df_pokemon['height_m'].fillna(df_pokemon['height_m'].mean(), inplace=True)

# Thay thế giá trị trong weight_kg bằng Mode của tất cả các cột
df_pokemon['weight_kg'].fillna(df_pokemon['weight_kg'].mean(), inplace=True)

# Thêm total abilities mà pokemon có
df_pokemon["tot_abilities"] = df_pokemon.apply(lambda x: len(x["abilities"]), axis=1)

# hợp nhất type1 và type2 thành cột mới type
# đổi tên type 1 thành primary và type 2 thành secondary
df_pokemon['type'] =  df_pokemon.apply(lambda x: x['type1'] if pd.isnull(x['type2']) else f'{x["type1"]}_{x["type2"]}', axis=1)
df_pokemon.rename(columns = {'type1':'primary type', 'type2':'secondary type'}, inplace = True)

import numpy   as np
import pandas  as pd
import seaborn as sns
from matplotlib import pyplot as plt

plt.figure(figsize=(16, 6))
ax = sns.boxplot(x='primary type', y='capture_rate', hue='is_legendary', data=df_pokemon)

ax.set_xlabel(xlabel='Primary Type')
ax.set_ylabel(ylabel='Capture Rate')
ax.set_title('Pokémon Capture Rate by Primary Type', pad=40)

sns.despine(top=True, right=True)

handles, labels = ax.get_legend_handles_labels()
ax.legend(handles, ['Non-legendary', 'Legendary'], loc=(1.1, 1.1))  # Adjusted legend position
plt.show()
